@startuml Examen 1
title Examen 1: Hobbies

!include clases/1/persona.iuml
!include clases/1/hobbies.iuml
!include clases/1/e_sexo.iuml
!include clases/1/e_hobbies.iuml

Persona "*" -l- "*" Hobbies : Aficiones

@enduml

'---------------------------------------------------------------------------
@startuml Examen 5
title Examen 5: Pedidos Virtuales
!include clases/5/foto.iuml
!include clases/5/linea.iuml
!include clases/5/pedido.iuml
!include clases/5/producto.iuml
!include clases/5/usuario.iuml

Usuario *-- "*" Pedido
Pedido "*" -- "*" Producto
Producto *-r- "*" Foto

Línea "*" -l-* Pedido
Línea "*" --* Producto

' La clase Línea hace referencia a cada una de las líneas de un ticket.
' La clase Foto alberga todas las n fotos que va a tener un Producto

@enduml

'---------------------------------------------------------------------------
@startuml Examen 7
title Examen 7: Acogida de Animales

!include clases/7/Especie.iuml
!include clases/7/Raza.iuml
!include clases/7/Animal.iuml
!include clases/7/Ingreso.iuml
!include clases/7/Abandono.iuml
!include clases/7/Entrega.iuml
!include clases/7/Persona.iuml
!include clases/7/Adopcion.iuml

Raza "*" -r-* Especie
Animal "*" -u-* Raza
Ingreso "*" -u-* Animal : recibido
(Abandono, Entrega) -u-> Ingreso : {Completo, Disjunto}
Entrega "*" -l-* Persona
Persona "0 1" -- "*" Ingreso
(Persona, Ingreso) .. Adopción

@enduml

'---------------------------------------------------------------------------
@startuml Examen 8 
title Examen 8: Teatro

!include clases/8/Espectaculo.iuml
!include clases/8/precio.iuml
!include clases/8/representacion.iuml
!include clases/8/TipoEspectaculo.iuml
!include clases/8/Zona.iuml
!include clases/8/Localidad.iuml
!include clases/8/entrada.iuml
!include clases/8/e_canal.iuml
!include clases/8/e_prueba.iuml

Espectaculo -u-* TipoEspectaculo : contiene
Representacion -u-* Espectaculo : esRepresentado
Zona "*" -r- "*" TipoEspectaculo : tienePrecio
Localidad -u-* Zona : contiene
Localidad "*" -- "*" Representacion : estaOcupada
(Zona, TipoEspectaculo) .. Precio
(Localidad, Representacion) .. Entrada
@enduml

'---------------------------------------------------------------------------